// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/create.proto

package com.rps.types.request.v1;

public final class CreateProto {
  private CreateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rps_types_request_v1_Create_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rps_types_request_v1_Create_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!rps/types/request/v1/create.proto\022\024rps" +
      ".types.request.v1\032\024gogoproto/gogo.proto\"" +
      "|\n\006Create\022#\n\rvalidate_only\030\001 \001(\010R\014valida" +
      "teOnly\022,\n\nrequest_id\030\002 \001(\tB\r\342\336\037\tRequestI" +
      "DR\trequestId\022\037\n\013skip_result\030\003 \001(\010R\nskipR" +
      "esultB\257\001\n\030com.rps.types.request.v1B\013Crea" +
      "teProtoP\001ZPgithub.azc.ext.hp.com/hp-rps/" +
      "api-rps-proto-go/api/rps/types/request/v" +
      "1;requestv1\242\002\003RTR\252\002\024Rps.Types.Request.V1" +
      "\312\002\024Rps\\Types\\Request\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_rps_types_request_v1_Create_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rps_types_request_v1_Create_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rps_types_request_v1_Create_descriptor,
        new java.lang.String[] { "ValidateOnly", "RequestId", "SkipResult", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customname);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
