// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/create.proto

package com.rps.types.request.v1;

public interface CreateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rps.types.request.v1.Create)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dry run, validate the request but skip resource creation.
   * Defaults to false
   * </pre>
   *
   * <code>bool validate_only = 1 [json_name = "validateOnly"];</code>
   * @return The validateOnly.
   */
  boolean getValidateOnly();

  /**
   * <pre>
   * Unique id for the server to track duplicate requests.
   * Required format is UUIDv4
   * </pre>
   *
   * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * Unique id for the server to track duplicate requests.
   * Required format is UUIDv4
   * </pre>
   *
   * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * Do not return the newly created resource in the RPC response.
   * Defaults to false
   * </pre>
   *
   * <code>bool skip_result = 3 [json_name = "skipResult"];</code>
   * @return The skipResult.
   */
  boolean getSkipResult();
}
