// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/create.proto

package com.rps.types.request.v1;

/**
 * <pre>
 * Generic create params inplemented by all CRUD style create methods.
 * </pre>
 *
 * Protobuf type {@code rps.types.request.v1.Create}
 */
public final class Create extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rps.types.request.v1.Create)
    CreateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Create.newBuilder() to construct.
  private Create(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Create() {
    requestId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Create();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Create(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            validateOnly_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 24: {

            skipResult_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rps.types.request.v1.CreateProto.internal_static_rps_types_request_v1_Create_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rps.types.request.v1.CreateProto.internal_static_rps_types_request_v1_Create_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rps.types.request.v1.Create.class, com.rps.types.request.v1.Create.Builder.class);
  }

  public static final int VALIDATE_ONLY_FIELD_NUMBER = 1;
  private boolean validateOnly_;
  /**
   * <pre>
   * Dry run, validate the request but skip resource creation.
   * Defaults to false
   * </pre>
   *
   * <code>bool validate_only = 1 [json_name = "validateOnly"];</code>
   * @return The validateOnly.
   */
  @java.lang.Override
  public boolean getValidateOnly() {
    return validateOnly_;
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object requestId_;
  /**
   * <pre>
   * Unique id for the server to track duplicate requests.
   * Required format is UUIDv4
   * </pre>
   *
   * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique id for the server to track duplicate requests.
   * Required format is UUIDv4
   * </pre>
   *
   * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKIP_RESULT_FIELD_NUMBER = 3;
  private boolean skipResult_;
  /**
   * <pre>
   * Do not return the newly created resource in the RPC response.
   * Defaults to false
   * </pre>
   *
   * <code>bool skip_result = 3 [json_name = "skipResult"];</code>
   * @return The skipResult.
   */
  @java.lang.Override
  public boolean getSkipResult() {
    return skipResult_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (validateOnly_ != false) {
      output.writeBool(1, validateOnly_);
    }
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestId_);
    }
    if (skipResult_ != false) {
      output.writeBool(3, skipResult_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (validateOnly_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, validateOnly_);
    }
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestId_);
    }
    if (skipResult_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, skipResult_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rps.types.request.v1.Create)) {
      return super.equals(obj);
    }
    com.rps.types.request.v1.Create other = (com.rps.types.request.v1.Create) obj;

    if (getValidateOnly()
        != other.getValidateOnly()) return false;
    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (getSkipResult()
        != other.getSkipResult()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALIDATE_ONLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getValidateOnly());
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + SKIP_RESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkipResult());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rps.types.request.v1.Create parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Create parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Create parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rps.types.request.v1.Create parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Create parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Create parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rps.types.request.v1.Create prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Generic create params inplemented by all CRUD style create methods.
   * </pre>
   *
   * Protobuf type {@code rps.types.request.v1.Create}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rps.types.request.v1.Create)
      com.rps.types.request.v1.CreateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rps.types.request.v1.CreateProto.internal_static_rps_types_request_v1_Create_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rps.types.request.v1.CreateProto.internal_static_rps_types_request_v1_Create_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rps.types.request.v1.Create.class, com.rps.types.request.v1.Create.Builder.class);
    }

    // Construct using com.rps.types.request.v1.Create.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      validateOnly_ = false;

      requestId_ = "";

      skipResult_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rps.types.request.v1.CreateProto.internal_static_rps_types_request_v1_Create_descriptor;
    }

    @java.lang.Override
    public com.rps.types.request.v1.Create getDefaultInstanceForType() {
      return com.rps.types.request.v1.Create.getDefaultInstance();
    }

    @java.lang.Override
    public com.rps.types.request.v1.Create build() {
      com.rps.types.request.v1.Create result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rps.types.request.v1.Create buildPartial() {
      com.rps.types.request.v1.Create result = new com.rps.types.request.v1.Create(this);
      result.validateOnly_ = validateOnly_;
      result.requestId_ = requestId_;
      result.skipResult_ = skipResult_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rps.types.request.v1.Create) {
        return mergeFrom((com.rps.types.request.v1.Create)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rps.types.request.v1.Create other) {
      if (other == com.rps.types.request.v1.Create.getDefaultInstance()) return this;
      if (other.getValidateOnly() != false) {
        setValidateOnly(other.getValidateOnly());
      }
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (other.getSkipResult() != false) {
        setSkipResult(other.getSkipResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rps.types.request.v1.Create parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rps.types.request.v1.Create) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean validateOnly_ ;
    /**
     * <pre>
     * Dry run, validate the request but skip resource creation.
     * Defaults to false
     * </pre>
     *
     * <code>bool validate_only = 1 [json_name = "validateOnly"];</code>
     * @return The validateOnly.
     */
    @java.lang.Override
    public boolean getValidateOnly() {
      return validateOnly_;
    }
    /**
     * <pre>
     * Dry run, validate the request but skip resource creation.
     * Defaults to false
     * </pre>
     *
     * <code>bool validate_only = 1 [json_name = "validateOnly"];</code>
     * @param value The validateOnly to set.
     * @return This builder for chaining.
     */
    public Builder setValidateOnly(boolean value) {
      
      validateOnly_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dry run, validate the request but skip resource creation.
     * Defaults to false
     * </pre>
     *
     * <code>bool validate_only = 1 [json_name = "validateOnly"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValidateOnly() {
      
      validateOnly_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * Unique id for the server to track duplicate requests.
     * Required format is UUIDv4
     * </pre>
     *
     * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique id for the server to track duplicate requests.
     * Required format is UUIDv4
     * </pre>
     *
     * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique id for the server to track duplicate requests.
     * Required format is UUIDv4
     * </pre>
     *
     * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique id for the server to track duplicate requests.
     * Required format is UUIDv4
     * </pre>
     *
     * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique id for the server to track duplicate requests.
     * Required format is UUIDv4
     * </pre>
     *
     * <code>string request_id = 2 [json_name = "requestId", (.gogoproto.customname) = "RequestID"];</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private boolean skipResult_ ;
    /**
     * <pre>
     * Do not return the newly created resource in the RPC response.
     * Defaults to false
     * </pre>
     *
     * <code>bool skip_result = 3 [json_name = "skipResult"];</code>
     * @return The skipResult.
     */
    @java.lang.Override
    public boolean getSkipResult() {
      return skipResult_;
    }
    /**
     * <pre>
     * Do not return the newly created resource in the RPC response.
     * Defaults to false
     * </pre>
     *
     * <code>bool skip_result = 3 [json_name = "skipResult"];</code>
     * @param value The skipResult to set.
     * @return This builder for chaining.
     */
    public Builder setSkipResult(boolean value) {
      
      skipResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Do not return the newly created resource in the RPC response.
     * Defaults to false
     * </pre>
     *
     * <code>bool skip_result = 3 [json_name = "skipResult"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipResult() {
      
      skipResult_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rps.types.request.v1.Create)
  }

  // @@protoc_insertion_point(class_scope:rps.types.request.v1.Create)
  private static final com.rps.types.request.v1.Create DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rps.types.request.v1.Create();
  }

  public static com.rps.types.request.v1.Create getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Create>
      PARSER = new com.google.protobuf.AbstractParser<Create>() {
    @java.lang.Override
    public Create parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Create(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Create> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Create> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rps.types.request.v1.Create getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

