// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/delete.proto

package com.rps.types.request.v1;

public final class DeleteProto {
  private DeleteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rps_types_request_v1_Delete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rps_types_request_v1_Delete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!rps/types/request/v1/delete.proto\022\024rps" +
      ".types.request.v1\"\034\n\006Delete\022\022\n\004soft\030\001 \001(" +
      "\010R\004softB\257\001\n\030com.rps.types.request.v1B\013De" +
      "leteProtoP\001ZPgithub.azc.ext.hp.com/hp-rp" +
      "s/api-rps-proto-go/api/rps/types/request" +
      "/v1;requestv1\242\002\003RTR\252\002\024Rps.Types.Request." +
      "V1\312\002\024Rps\\Types\\Request\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rps_types_request_v1_Delete_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rps_types_request_v1_Delete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rps_types_request_v1_Delete_descriptor,
        new java.lang.String[] { "Soft", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
