// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/delete.proto

package com.rps.types.request.v1;

/**
 * <pre>
 * Generic delete params inplemented by all CRUD style delete methods.
 * </pre>
 *
 * Protobuf type {@code rps.types.request.v1.Delete}
 */
public final class Delete extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rps.types.request.v1.Delete)
    DeleteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Delete.newBuilder() to construct.
  private Delete(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Delete() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Delete();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Delete(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            soft_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rps.types.request.v1.DeleteProto.internal_static_rps_types_request_v1_Delete_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rps.types.request.v1.DeleteProto.internal_static_rps_types_request_v1_Delete_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rps.types.request.v1.Delete.class, com.rps.types.request.v1.Delete.Builder.class);
  }

  public static final int SOFT_FIELD_NUMBER = 1;
  private boolean soft_;
  /**
   * <pre>
   * If true, soft-delete the resource.
   * Defaults to false
   * </pre>
   *
   * <code>bool soft = 1 [json_name = "soft"];</code>
   * @return The soft.
   */
  @java.lang.Override
  public boolean getSoft() {
    return soft_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (soft_ != false) {
      output.writeBool(1, soft_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (soft_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, soft_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rps.types.request.v1.Delete)) {
      return super.equals(obj);
    }
    com.rps.types.request.v1.Delete other = (com.rps.types.request.v1.Delete) obj;

    if (getSoft()
        != other.getSoft()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOFT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSoft());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rps.types.request.v1.Delete parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Delete parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Delete parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rps.types.request.v1.Delete parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Delete parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Delete parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rps.types.request.v1.Delete prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Generic delete params inplemented by all CRUD style delete methods.
   * </pre>
   *
   * Protobuf type {@code rps.types.request.v1.Delete}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rps.types.request.v1.Delete)
      com.rps.types.request.v1.DeleteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rps.types.request.v1.DeleteProto.internal_static_rps_types_request_v1_Delete_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rps.types.request.v1.DeleteProto.internal_static_rps_types_request_v1_Delete_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rps.types.request.v1.Delete.class, com.rps.types.request.v1.Delete.Builder.class);
    }

    // Construct using com.rps.types.request.v1.Delete.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      soft_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rps.types.request.v1.DeleteProto.internal_static_rps_types_request_v1_Delete_descriptor;
    }

    @java.lang.Override
    public com.rps.types.request.v1.Delete getDefaultInstanceForType() {
      return com.rps.types.request.v1.Delete.getDefaultInstance();
    }

    @java.lang.Override
    public com.rps.types.request.v1.Delete build() {
      com.rps.types.request.v1.Delete result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rps.types.request.v1.Delete buildPartial() {
      com.rps.types.request.v1.Delete result = new com.rps.types.request.v1.Delete(this);
      result.soft_ = soft_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rps.types.request.v1.Delete) {
        return mergeFrom((com.rps.types.request.v1.Delete)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rps.types.request.v1.Delete other) {
      if (other == com.rps.types.request.v1.Delete.getDefaultInstance()) return this;
      if (other.getSoft() != false) {
        setSoft(other.getSoft());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rps.types.request.v1.Delete parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rps.types.request.v1.Delete) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean soft_ ;
    /**
     * <pre>
     * If true, soft-delete the resource.
     * Defaults to false
     * </pre>
     *
     * <code>bool soft = 1 [json_name = "soft"];</code>
     * @return The soft.
     */
    @java.lang.Override
    public boolean getSoft() {
      return soft_;
    }
    /**
     * <pre>
     * If true, soft-delete the resource.
     * Defaults to false
     * </pre>
     *
     * <code>bool soft = 1 [json_name = "soft"];</code>
     * @param value The soft to set.
     * @return This builder for chaining.
     */
    public Builder setSoft(boolean value) {
      
      soft_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, soft-delete the resource.
     * Defaults to false
     * </pre>
     *
     * <code>bool soft = 1 [json_name = "soft"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSoft() {
      
      soft_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rps.types.request.v1.Delete)
  }

  // @@protoc_insertion_point(class_scope:rps.types.request.v1.Delete)
  private static final com.rps.types.request.v1.Delete DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rps.types.request.v1.Delete();
  }

  public static com.rps.types.request.v1.Delete getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Delete>
      PARSER = new com.google.protobuf.AbstractParser<Delete>() {
    @java.lang.Override
    public Delete parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Delete(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Delete> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Delete> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rps.types.request.v1.Delete getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

