// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/get.proto

package com.rps.types.request.v1;

/**
 * <pre>
 * Generic get params inplemented by all CRUD style get methods.
 * </pre>
 *
 * Protobuf type {@code rps.types.request.v1.Get}
 */
public final class Get extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rps.types.request.v1.Get)
    GetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Get.newBuilder() to construct.
  private Get(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Get() {
    fieldMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Get();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Get(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fieldMask_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            fieldMask_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fieldMask_ = fieldMask_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rps.types.request.v1.GetProto.internal_static_rps_types_request_v1_Get_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rps.types.request.v1.GetProto.internal_static_rps_types_request_v1_Get_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rps.types.request.v1.Get.class, com.rps.types.request.v1.Get.Builder.class);
  }

  public static final int FIELD_MASK_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList fieldMask_;
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @return A list containing the fieldMask.
   */
  public com.google.protobuf.ProtocolStringList
      getFieldMaskList() {
    return fieldMask_;
  }
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @return The count of fieldMask.
   */
  public int getFieldMaskCount() {
    return fieldMask_.size();
  }
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @param index The index of the element to return.
   * @return The fieldMask at the given index.
   */
  public java.lang.String getFieldMask(int index) {
    return fieldMask_.get(index);
  }
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fieldMask at the given index.
   */
  public com.google.protobuf.ByteString
      getFieldMaskBytes(int index) {
    return fieldMask_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fieldMask_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldMask_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < fieldMask_.size(); i++) {
        dataSize += computeStringSizeNoTag(fieldMask_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFieldMaskList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rps.types.request.v1.Get)) {
      return super.equals(obj);
    }
    com.rps.types.request.v1.Get other = (com.rps.types.request.v1.Get) obj;

    if (!getFieldMaskList()
        .equals(other.getFieldMaskList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFieldMaskCount() > 0) {
      hash = (37 * hash) + FIELD_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getFieldMaskList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rps.types.request.v1.Get parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Get parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rps.types.request.v1.Get parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rps.types.request.v1.Get parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Get parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rps.types.request.v1.Get parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rps.types.request.v1.Get prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Generic get params inplemented by all CRUD style get methods.
   * </pre>
   *
   * Protobuf type {@code rps.types.request.v1.Get}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rps.types.request.v1.Get)
      com.rps.types.request.v1.GetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rps.types.request.v1.GetProto.internal_static_rps_types_request_v1_Get_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rps.types.request.v1.GetProto.internal_static_rps_types_request_v1_Get_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rps.types.request.v1.Get.class, com.rps.types.request.v1.Get.Builder.class);
    }

    // Construct using com.rps.types.request.v1.Get.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fieldMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rps.types.request.v1.GetProto.internal_static_rps_types_request_v1_Get_descriptor;
    }

    @java.lang.Override
    public com.rps.types.request.v1.Get getDefaultInstanceForType() {
      return com.rps.types.request.v1.Get.getDefaultInstance();
    }

    @java.lang.Override
    public com.rps.types.request.v1.Get build() {
      com.rps.types.request.v1.Get result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rps.types.request.v1.Get buildPartial() {
      com.rps.types.request.v1.Get result = new com.rps.types.request.v1.Get(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        fieldMask_ = fieldMask_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.fieldMask_ = fieldMask_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rps.types.request.v1.Get) {
        return mergeFrom((com.rps.types.request.v1.Get)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rps.types.request.v1.Get other) {
      if (other == com.rps.types.request.v1.Get.getDefaultInstance()) return this;
      if (!other.fieldMask_.isEmpty()) {
        if (fieldMask_.isEmpty()) {
          fieldMask_ = other.fieldMask_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFieldMaskIsMutable();
          fieldMask_.addAll(other.fieldMask_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rps.types.request.v1.Get parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rps.types.request.v1.Get) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList fieldMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFieldMaskIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fieldMask_ = new com.google.protobuf.LazyStringArrayList(fieldMask_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @return A list containing the fieldMask.
     */
    public com.google.protobuf.ProtocolStringList
        getFieldMaskList() {
      return fieldMask_.getUnmodifiableView();
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @return The count of fieldMask.
     */
    public int getFieldMaskCount() {
      return fieldMask_.size();
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @param index The index of the element to return.
     * @return The fieldMask at the given index.
     */
    public java.lang.String getFieldMask(int index) {
      return fieldMask_.get(index);
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the fieldMask at the given index.
     */
    public com.google.protobuf.ByteString
        getFieldMaskBytes(int index) {
      return fieldMask_.getByteString(index);
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @param index The index to set the value at.
     * @param value The fieldMask to set.
     * @return This builder for chaining.
     */
    public Builder setFieldMask(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldMaskIsMutable();
      fieldMask_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @param value The fieldMask to add.
     * @return This builder for chaining.
     */
    public Builder addFieldMask(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldMaskIsMutable();
      fieldMask_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @param values The fieldMask to add.
     * @return This builder for chaining.
     */
    public Builder addAllFieldMask(
        java.lang.Iterable<java.lang.String> values) {
      ensureFieldMaskIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fieldMask_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFieldMask() {
      fieldMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of fields to populate from the resource in the result.
     * // Defaults to empty, If empty all fields will be populated.
     * ID is always populated
     * </pre>
     *
     * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
     * @param value The bytes of the fieldMask to add.
     * @return This builder for chaining.
     */
    public Builder addFieldMaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFieldMaskIsMutable();
      fieldMask_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rps.types.request.v1.Get)
  }

  // @@protoc_insertion_point(class_scope:rps.types.request.v1.Get)
  private static final com.rps.types.request.v1.Get DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rps.types.request.v1.Get();
  }

  public static com.rps.types.request.v1.Get getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Get>
      PARSER = new com.google.protobuf.AbstractParser<Get>() {
    @java.lang.Override
    public Get parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Get(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Get> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Get> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rps.types.request.v1.Get getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

