// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/get.proto

package com.rps.types.request.v1;

public interface GetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rps.types.request.v1.Get)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @return A list containing the fieldMask.
   */
  java.util.List<java.lang.String>
      getFieldMaskList();
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @return The count of fieldMask.
   */
  int getFieldMaskCount();
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @param index The index of the element to return.
   * @return The fieldMask at the given index.
   */
  java.lang.String getFieldMask(int index);
  /**
   * <pre>
   * List of fields to populate from the resource in the result.
   * // Defaults to empty, If empty all fields will be populated.
   * ID is always populated
   * </pre>
   *
   * <code>repeated string field_mask = 1 [json_name = "fieldMask"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fieldMask at the given index.
   */
  com.google.protobuf.ByteString
      getFieldMaskBytes(int index);
}
