// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/types/request/v1/get.proto

package com.rps.types.request.v1;

public final class GetProto {
  private GetProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rps_types_request_v1_Get_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rps_types_request_v1_Get_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036rps/types/request/v1/get.proto\022\024rps.ty" +
      "pes.request.v1\"$\n\003Get\022\035\n\nfield_mask\030\001 \003(" +
      "\tR\tfieldMaskB\254\001\n\030com.rps.types.request.v" +
      "1B\010GetProtoP\001ZPgithub.azc.ext.hp.com/hp-" +
      "rps/api-rps-proto-go/api/rps/types/reque" +
      "st/v1;requestv1\242\002\003RTR\252\002\024Rps.Types.Reques" +
      "t.V1\312\002\024Rps\\Types\\Request\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rps_types_request_v1_Get_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rps_types_request_v1_Get_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rps_types_request_v1_Get_descriptor,
        new java.lang.String[] { "FieldMask", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
