version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017-27019:27017-27019

  jaeger-allinone:
    image: jaegertracing/all-in-one:1.9
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268

  broker:
    image: nats:latest
    ports:
      - 4222:4222
    command: ["-js"]