version: "3"

services:
  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    ports:
      - 27017-27019:27017-27019

  broker:
    image: nats:latest
    ports:
      - 4222:4222
    command: ["-js"]