# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).


scrape_configs:
  - job_name: 'svc-rps-support-ticket-spring-boot-prometheus'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9090']
      # change to yours ip
      # https://github.com/docker/docker.github.io/issues/6012

  - job_name: 'svc-rps-support-ticket-app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]