// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rps/types/request/v1/create.proto

package requestv1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Generic create params inplemented by all CRUD style create methods.
type Create struct {
	// Dry run, validate the request but skip resource creation.
	// Defaults to false
	ValidateOnly bool `protobuf:"varint,1,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	// Unique id for the server to track duplicate requests.
	// Required format is UUIDv4
	RequestID string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Do not return the newly created resource in the RPC response.
	// Defaults to false
	SkipResult bool `protobuf:"varint,3,opt,name=skip_result,json=skipResult,proto3" json:"skip_result,omitempty"`
}

func (m *Create) Reset()      { *m = Create{} }
func (*Create) ProtoMessage() {}
func (*Create) Descriptor() ([]byte, []int) {
	return fileDescriptor_3efdfb5c44de52a2, []int{0}
}
func (m *Create) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Create) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Create.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Create) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create.Merge(m, src)
}
func (m *Create) XXX_Size() int {
	return m.Size()
}
func (m *Create) XXX_DiscardUnknown() {
	xxx_messageInfo_Create.DiscardUnknown(m)
}

var xxx_messageInfo_Create proto.InternalMessageInfo

func (m *Create) GetValidateOnly() bool {
	if m != nil {
		return m.ValidateOnly
	}
	return false
}

func (m *Create) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *Create) GetSkipResult() bool {
	if m != nil {
		return m.SkipResult
	}
	return false
}

func init() {
	proto.RegisterType((*Create)(nil), "rps.types.request.v1.Create")
}

func init() { proto.RegisterFile("rps/types/request/v1/create.proto", fileDescriptor_3efdfb5c44de52a2) }

var fileDescriptor_3efdfb5c44de52a2 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc2, 0x40,
	0x18, 0xc7, 0x7b, 0x90, 0x10, 0x39, 0x64, 0x69, 0x18, 0x1a, 0x87, 0x0f, 0xd4, 0x85, 0x41, 0xae,
	0x69, 0x1c, 0xdd, 0xd0, 0x85, 0x49, 0x72, 0x21, 0x0c, 0x86, 0x84, 0x94, 0x72, 0x29, 0x8d, 0x85,
	0x3b, 0x7b, 0x47, 0x23, 0xc6, 0xc1, 0x47, 0xf0, 0x19, 0x9c, 0x8c, 0x4f, 0x62, 0x9c, 0x18, 0x99,
	0x8c, 0x5c, 0x17, 0x47, 0x1e, 0xc1, 0xf4, 0xa8, 0x1b, 0xd3, 0x7d, 0xf9, 0xe5, 0x77, 0xdf, 0x97,
	0xff, 0x1f, 0x9f, 0x26, 0x42, 0xba, 0x6a, 0x25, 0x98, 0x74, 0x13, 0xf6, 0xb0, 0x64, 0x52, 0xb9,
	0xa9, 0xe7, 0x06, 0x09, 0xf3, 0x15, 0x23, 0x22, 0xe1, 0x8a, 0xdb, 0x8d, 0x44, 0x48, 0x62, 0x14,
	0x52, 0x28, 0x24, 0xf5, 0x4e, 0x1a, 0x21, 0x0f, 0xb9, 0x11, 0xdc, 0x7c, 0xda, 0xbb, 0x67, 0xcf,
	0xb8, 0x72, 0x6d, 0xfe, 0xda, 0xe7, 0xb8, 0x9e, 0xfa, 0x71, 0x34, 0xf5, 0x15, 0x1b, 0xf3, 0x45,
	0xbc, 0x72, 0x50, 0x0b, 0xb5, 0x8f, 0xe8, 0xf1, 0x3f, 0xbc, 0x5d, 0xc4, 0x2b, 0xfb, 0x02, 0xe3,
	0x62, 0xe5, 0x38, 0x9a, 0x3a, 0xa5, 0x16, 0x6a, 0x57, 0xbb, 0x75, 0xfd, 0xdd, 0xac, 0xd2, 0x3d,
	0xed, 0xdd, 0xd0, 0x6a, 0x21, 0xf4, 0xa6, 0x76, 0x13, 0xd7, 0xe4, 0x7d, 0x24, 0xc6, 0x09, 0x93,
	0xcb, 0x58, 0x39, 0x65, 0xb3, 0x10, 0xe7, 0x88, 0x1a, 0xd2, 0xcd, 0xd0, 0x7a, 0x0b, 0xd6, 0x66,
	0x0b, 0xd6, 0x6e, 0x0b, 0xe8, 0x45, 0x03, 0x7a, 0xd7, 0x80, 0x3e, 0x35, 0xa0, 0xb5, 0x06, 0xf4,
	0xa3, 0x01, 0xfd, 0x6a, 0xb0, 0x76, 0x1a, 0xd0, 0x6b, 0x06, 0xd6, 0x3a, 0x03, 0x6b, 0x93, 0x81,
	0x85, 0x9d, 0x80, 0xcf, 0xc9, 0xa1, 0x90, 0xdd, 0xda, 0x3e, 0x4c, 0x3f, 0xcf, 0xd6, 0x47, 0x77,
	0xfd, 0x30, 0x52, 0xb3, 0xe5, 0x84, 0xf8, 0x4f, 0x01, 0x61, 0x8f, 0x8a, 0xcc, 0x04, 0x09, 0xf8,
	0xdc, 0x9d, 0x89, 0x4e, 0xde, 0xa2, 0x2f, 0xa2, 0xfc, 0xed, 0x98, 0x26, 0x3a, 0x21, 0xcf, 0x81,
	0x7b, 0xa8, 0xde, 0xab, 0x62, 0x4c, 0xbd, 0xb7, 0x52, 0x99, 0x0e, 0xe8, 0x47, 0xa9, 0x41, 0x85,
	0x24, 0x03, 0x73, 0xbd, 0x48, 0x4e, 0x86, 0xde, 0x97, 0xc1, 0x23, 0x83, 0x47, 0x05, 0x1e, 0x0d,
	0xbd, 0x49, 0xc5, 0x1c, 0xb8, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xd2, 0x92, 0x14, 0xbb,
	0x01, 0x00, 0x00,
}

func (this *Create) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Create)
	if !ok {
		that2, ok := that.(Create)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ValidateOnly != that1.ValidateOnly {
		return false
	}
	if this.RequestID != that1.RequestID {
		return false
	}
	if this.SkipResult != that1.SkipResult {
		return false
	}
	return true
}
func (this *Create) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&requestv1.Create{")
	s = append(s, "ValidateOnly: "+fmt.Sprintf("%#v", this.ValidateOnly)+",\n")
	s = append(s, "RequestID: "+fmt.Sprintf("%#v", this.RequestID)+",\n")
	s = append(s, "SkipResult: "+fmt.Sprintf("%#v", this.SkipResult)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringCreate(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Create) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Create) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Create) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SkipResult {
		i--
		if m.SkipResult {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.RequestID) > 0 {
		i -= len(m.RequestID)
		copy(dAtA[i:], m.RequestID)
		i = encodeVarintCreate(dAtA, i, uint64(len(m.RequestID)))
		i--
		dAtA[i] = 0x12
	}
	if m.ValidateOnly {
		i--
		if m.ValidateOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCreate(dAtA []byte, offset int, v uint64) int {
	offset -= sovCreate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Create) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidateOnly {
		n += 2
	}
	l = len(m.RequestID)
	if l > 0 {
		n += 1 + l + sovCreate(uint64(l))
	}
	if m.SkipResult {
		n += 2
	}
	return n
}

func sovCreate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCreate(x uint64) (n int) {
	return sovCreate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Create) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Create{`,
		`ValidateOnly:` + fmt.Sprintf("%v", this.ValidateOnly) + `,`,
		`RequestID:` + fmt.Sprintf("%v", this.RequestID) + `,`,
		`SkipResult:` + fmt.Sprintf("%v", this.SkipResult) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringCreate(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Create) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCreate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Create: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Create: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidateOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ValidateOnly = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCreate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCreate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipResult", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCreate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SkipResult = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCreate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCreate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCreate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCreate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCreate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCreate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCreate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCreate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCreate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCreate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCreate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCreate = fmt.Errorf("proto: unexpected end of group")
)
