spring:
  application:
    name: supportTicketService
  data:
    mongodb:
      host: localhost
      database: rps_ticket
      port: 27017
      
logging:
  level:
    org.springframework: ERROR
    com.TicketService.supportTicketService: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
  
  
  