management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    export:
      atlas:
        enabled: false
  security:
    enabled: false

spring:
  application:
    name: svc-rps-support-ticket
  data:
    mongo-database:
      host: localhost
      port: 27017
      auto-index-creation: true

logging:
  level:
    org.springframework: ERROR
    com.TicketService.supportTicketService: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
  
  
  