version: "3"
services:
 mymongodb:
   image: mongo:latest
   container_name: mymongodb
   ports:
     - 27017:27017
 support-ticketservice:
   image: support-ticketservice:1.0
   container_name: support-ticketservice
   ports:
     - 8080:8080
   links:
     - mymongodb 