// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/options/method.proto

package com.rps.options;

public final class MethodProto {
  private MethodProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.rps.options.MethodProto.method);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int METHOD_FIELD_NUMBER = 50007;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      com.rps.options.MethodRule> method = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.rps.options.MethodRule.class,
        com.rps.options.MethodRule.getDefaultInstance());
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rps_options_MethodRule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rps_options_MethodRule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030rps/options/method.proto\022\013rps.options\032" +
      " google/protobuf/descriptor.proto\"$\n\nMet" +
      "hodRule\022\026\n\006scopes\030\001 \003(\tR\006scopes:Q\n\006metho" +
      "d\022\036.google.protobuf.MethodOptions\030\327\206\003 \001(" +
      "\0132\027.rps.options.MethodRuleR\006methodBu\n\017co" +
      "m.rps.optionsB\013MethodProtoP\001ZEgithub.azc" +
      ".ext.hp.com/hp-rps/api-rps-proto-go/api/" +
      "rps/options;options\252\002\013Hpc.Optionsb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_rps_options_MethodRule_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rps_options_MethodRule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rps_options_MethodRule_descriptor,
        new java.lang.String[] { "Scopes", });
    method.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
