// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps/options/method.proto

package com.rps.options;

public interface MethodRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rps.options.MethodRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Scopes defines the scopes needed to call this endpoint.
   * </pre>
   *
   * <code>repeated string scopes = 1 [json_name = "scopes"];</code>
   * @return A list containing the scopes.
   */
  java.util.List<java.lang.String>
      getScopesList();
  /**
   * <pre>
   * Scopes defines the scopes needed to call this endpoint.
   * </pre>
   *
   * <code>repeated string scopes = 1 [json_name = "scopes"];</code>
   * @return The count of scopes.
   */
  int getScopesCount();
  /**
   * <pre>
   * Scopes defines the scopes needed to call this endpoint.
   * </pre>
   *
   * <code>repeated string scopes = 1 [json_name = "scopes"];</code>
   * @param index The index of the element to return.
   * @return The scopes at the given index.
   */
  java.lang.String getScopes(int index);
  /**
   * <pre>
   * Scopes defines the scopes needed to call this endpoint.
   * </pre>
   *
   * <code>repeated string scopes = 1 [json_name = "scopes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the scopes at the given index.
   */
  com.google.protobuf.ByteString
      getScopesBytes(int index);
}
